### ISSUE TITLE
Remove sys.setdefaultencoding

### ISSUE THREAD

**Issue by christianmlong** [oasis-open/csaf-parser#2]
At the top of main(), the function sets the default encoding to utf-8 using the `sys.setdefaultencoding` trick.

    reload(sys)
    sys.setdefaultencoding('utf8')

That can cause problems elsewhere, because it changes the default encoding for the whole interpreter. It would be better to explicitly decode to unicode on read, and encode back to bytestrings on write.

### References

https://anonbadger.wordpress.com/2015/06/16/why-sys-setdefaultencoding-will-break-code/
https://stackoverflow.com/questions/28657010/dangers-of-sys-setdefaultencodingutf-8/29561747#29561747
https://nedbatchelder.com/text/unipain.html
https://github.com/jdunck/python-unicodecsv

**Comment by christianmlong** [comment]
Here's an example of an error that the `sys.setdefaultencoding` hack is preventing.

```
Traceback (most recent call last):
  File "cvrf_util.py", line 825, in <module>
    main(progname)
  File "cvrf_util.py", line 818, in main
    cvrf_dispatch(cvrf_doc, parsables, args.collate_vuln, args.strip_ns, cvrf_version, output_format, output_file, args, related_product_tags)
  File "cvrf_util.py", line 342, in cvrf_dispatch
    cvrf_dump(results, strip_ns, output_format, cvrf_doc, cvrf_version, args, related_product_tags)
  File "cvrf_util.py", line 324, in cvrf_dump
    print_node(cvrf_doc, cvrf_version, args, output_format, item, strip_ns, f, related_product_tags)
  File "cvrf_util.py", line 280, in print_node
    writer.writerow(row_data)
  File "/#######/lib/python2.7/codecs.py", line 706, in write
    return self.writer.write(data)
  File "/#######/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5007: ordinal not in range(128)
cvrf_util.py: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5007: ordinal not in range(128)
```
